app = 'watershed'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    type = "tcp"
    interval = "10s"
    timeout = "2s"
    grace_period = "60s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1